spinnaker/governance

- README.md
- code-of-conduct.md
- governance.md
- sig-lifecycle.md
Added code of conduct, governance (w/minor updates), and proposed SIG PR process. Updated README w/some contact information.
> Community documentation updates v1

- cloud_provider_requirements.md
First pass at the requirements for adding/keeping a cloud provider
> Add cloud provider requirements

- roadmap.md
> docs(roadmap): add ECS provider roadmap

- governance.md
removed SK and added A Phillips
> minor update to governance.md (remove SK, replace w/AP)

- sig-ui-ux/README.md
I realized I updated this on spinnaker.github.io (https://github.com/spinnaker/spinnaker.github.io/pull/1488) but not here!
> chore(docs): update UI SIG README

- governance.md
In line with https://www.spinnaker.io/community/governance/#technical-oversight-committee
> Update TOC members

- governance.md
First pass at refining aspects of the policy. 
1. clarified TOC nomination and approval process
2. same for SC
3. added notion of term limits + consecutiveness 
4. Chair person for both TOC and SC
5. Calendar year on Spinnaker Summit
> Proposed updates to governance policy from SC meeting

- committee-technical-oversight/README.md
https://github.com/spinnaker/community/issues/32
> docs(toc): Adding @plumpy to TOC

- governance.md
Added language encouraging what's best for the project
> Slight addition to duties & member of TOC

- rfc/.template.md
Aiming to have some better consistency and depth across our proposals.
> feat(docs): Adding RFC template

- sig-operational-validation/README.md
This is a proposal for an operational validation SIG.  See the commits for details.
> add documentation for Operational Validation SIG

- sig-documentation/README.md
Add 
* Meeting notes
* Meeting link
* Meeting time
These items were TBD while the SIG was forming.
> chore(SIG): update docs sig readme

- rfc/plugins.md
⚠️ This proposal is not intended to be all-things-considered. We're aiming to have a general direction down and then learn and adapt as development goes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spinnaker/community/43)
> feat(rfc): Plugins

- CODEOWNERS
Seeded with members of the TOC as _most_ PRs and changes involve us.
Happy to see further adjustments for the SC as needed.
> feat(*): Initial CODEOWNERS

- membership.yml
> chore(members): Add @gal-yardeni and @luispollo to oss-approvers

- sig-documentation/README.md
> Remove BK from SIG leads

- sig-aws/README.md
- added Jeyrs Chabu as lead from Netflix
> chore(*): Adding Jeyrs Chabu as Lead

- roadmap.md
Update ECS roadmap to reflect current work.
> Update Amazon ECS Roadmap

- sig-aws/README.md
I'd like to propose Akshay Dayal to be SIG lead for AWS instead of myself.  Akshay has done a wonderful job of helping to organize, demos and agenda for the SIG lead for the last 2 meetings.
> chore(aws): SIG Lead change proposal for AWS

- sig-ui-ux/README.md
Add UI SIG meeting link to README.
> chore(sig): update UI SIG meeting link

- rfc/.template.md
As discussed at the last TOC meeting.
> docs(rfc): add some guidance to RFC template about timelines

- committee-technical-oversight/sig-creation.md
Some internal docs for the TOC. Have I missed anything?
> chore(docs): Documenting manual steps involved in SIG creation

- rfc/legacy_artifacts_ui_removal.md
Adds RFC to remove the legacy artifacts UI.
> feat(rfc): add Legacy Artifacts UI Removal RFC

- membership.yml
- @claymccoy 
- @robzienert 
- Name of organization(s) with significant stake in project
-> Armory
- Links to public Spinnaker PRs
PRs
https://github.com/spinnaker/halyard/pull/1386
https://github.com/spinnaker/kork/pull/358
https://github.com/spinnaker/kork/pull/219
https://github.com/spinnaker/kork/pull/217
https://github.com/spinnaker/kork/pull/325
Reviews
https://github.com/spinnaker/community/pull/43
https://github.com/spinnaker/kork/pull/453
https://github.com/spinnaker/kork/pull/443
https://github.com/spinnaker/kork/pull/439
https://github.com/spinnaker/halyard/pull/1165
> add link108 to oss-approvers

- membership.yml
As per https://github.com/spinnaker/governance/issues/117
> chore(membership): Add Lorin Hochstein to reviewers

- membership.yml
As per https://github.com/spinnaker/governance/issues/118
> chore(membership): Add Dan Peach to approvers

- sig-spinnaker-as-code/README.md
we moved from biweekly to monthly, just a small tweak to the language.
> chore(sig-spinnaker-as-code): update meeting cadence to monthly

- membership.yml
Opening PR as a reminder for #121
> chore(members): Add @lorin to approvers

- rfc/eol_kubernetes_v1.md
- rfc/legacy_artifacts_ui_removal.md
* feat(rfc): update Kubernetes V1 EOL RFC 
* feat(rfc): update Legacy Artifacts Removal RFC 
* feat(rfc): mark Kubernetes V1 EOL RFC as implemented
> feat(rfc): update Kubernetes V1 and Legacy Artifacts Removal RFCs

- sig-cf/README.md
Proposing a SIG to focus on the Cloud Foundry (CF) clouddriver
> feat(sig): Submit proposal for a CF SIG

- scripts/create-sig-groups.main.kts
> Add a script to create SIG groups and clean up existing ones.

- rfc/website-revamp.md
Add functionality so a reader can copy a code block with the click of a button
> rfc(website-revamp): add item to copy code blocks

- scripts/create-sig-groups.main.kts
* Only one SIG lead is required
* Forgot to call .execute() a lot of places
* A group can not be a manager of another group, so add the SIG leads directly as managers of the SIG group
> Some create-sig-groups fixes after using it the first time:

- rfc/halyard-lite.md
This updates the RFC with progress and clarifications on things that were vague initially and where we have more concrete plans.
Please read the commits separately, the first one is just whitespace and is most of the diff.
> feat(rfc): Updates to kleat RFC

- sig-huaweicloud/README.md
Proposing a SIG to focus on the Huawei Cloud (HWC) clouddriver #126
> feat(sig): Submit proposal for a Huawei Cloud SIG

- sig-tencentcloud/README.md
Proposing SIG for Tencent Cloud provider.
https://github.com/spinnaker/governance/issues/128
> Submit proposal for TencentCloud SIG

- sig-oci/README.md
Update the SIG README with details about the monthly meetings on Google Meet and link to the Meeting Notes document.
> Add monthly meeting details

- rfc/ecs_e2e_tests.md
RFC which proposes Amazon ECS end to end tests + speculation on the future of alternatives.
> feat(rfc): Amazon ECS end to end tests

- sig-yandexcloud/README.md
Proposing a SIG to focus on the Yandex.Cloud clouddriver #166
> feat(sig): Submit proposal for a Yandex Cloud SIG

- sig-ui-ux/README.md
I'll be shifting my focus away from Deck for now, but I'm very excited to welcome @noahi as the next UI SIG co-lead! 🥳 👏 🎉
> feat(docs): replace maggieneterval@ with noahi@ as UI SIG co-lead

- rfc/account-registration-plugin.md
Proposal to add the dynamic account registration plugin to the Spinnaker plugin repository.
> feat(rfc): Dynamic account registration plugin

- sig-security/README.md
Proposal to assist with leadership of security sig
> chore(sig-security): Proposal to add myself to assist with sig-security leadership

- sig-azure/README.md
- sig-index.md
In today's (12/8/2020) SIG Azure meeting. it has been decided to move the meeting time from 8am PST to 10am PST>
> Update sig azure

- .github/ISSUE_TEMPLATE/plugin-ownership-transfer.md
> chore(core): Remove my username from one more template

- .github/ISSUE_TEMPLATE/approver-application.md
- .github/ISSUE_TEMPLATE/new-cloud-provider.md
- .github/ISSUE_TEMPLATE/plugin-ownership-transfer.md
- .github/ISSUE_TEMPLATE/reviewer-application.md
- CODEOWNERS
- committee-technical-oversight/README.md
- membership.yml
I'll be moving on from Armory and Spinnaker and starting a new adventure
in May so I'll be stepping down from the TOC. It's been a pleasure
working with everyone!
> chore(toc): remove ethanfrogers from toc

- membership.yml
depends on approval in https://github.com/spinnaker/governance/issues/234.
> add David Byron as a reviewer

- sig-aws/README.md
Based on this thread https://spinnakerteam.slack.com/archives/C091CCWRJ/p1621286097223200 putting my hand up to help out with the AWS SIG.
> Add Dan Everton as co-lead for the AWS SIG

- .github/ISSUE_TEMPLATE/approver-application.md
- .github/ISSUE_TEMPLATE/new-cloud-provider.md
- .github/ISSUE_TEMPLATE/plugin-ownership-transfer.md
- .github/ISSUE_TEMPLATE/reviewer-application.md
- CODEOWNERS
- committee-technical-oversight/README.md
- membership.yml
Removing myself from the TOC, as I've not been filling this role for basically the whole year.
> chore(docs): Removing @robzienert from TOC

- sig-aws/README.md
> chore(*): Stepping down as SIG Lead

- sig-aws/README.md
Adding myself as SIG Lead
A little context of who I am: My name is Ben Powell and I was at AWS for 5 and 1/2 years and am now apart of the Apple Spinnaker team. I would love to help as a lead in the SIG meetings.
Signed-off-by: benjamin_j_powell <benjamin_j_powell@apple.com>
> Adding Ben Powell as SIG Lead

- sig-googlecloud/README.md
Since Nirmalya is busy with other stuff, I wanted to nominate myself lead this SIG along with Michael Plump, Gopinath & Michael Graff.
> Replace Nirmalya with Vishal as SIG lead

- membership.yml
See https://github.com/spinnaker/governance/issues/267
> add @siddhu-opsmx as a reviewer

- sig-azure/README.md
- sig-googlecloud/README.md
Replace Edgar with Vishal as Azure SIG lead
> Replace Edgar with Vishal Patel as Azure SIG lead

- membership.yml
> Add mattgogerly as approver

- sig-kubernetes/README.md
I'll no longer be directly involved with Spinnaker
> chore(governance): Removing German from SIG

- membership.yml
https://github.com/spinnaker/governance/issues/300
> add nemesisOsorio as reviewer

- sig-azure/README.md
- sig-googlecloud/README.md
Updating the Azure SIG meeting invite & meeting notes document
> Azure SIG Meeting details

- membership.yml
Based on https://github.com/spinnaker/governance/issues/310
> feat(reviewer): Add ovidiupopa07 as reviewer

- membership.yml
re: https://github.com/spinnaker/governance/issues/309
> feat(reviewer): add mrampton as reviewer

- membership.yml
re: https://github.com/spinnaker/governance/issues/307
> feat(reviewer): add armory-abedonik as reviewer

- membership.yml
The @kskewes-sf account is no longer active.
> chore(reviewer): Remove kskewes-sf - now unused

- membership.yml
https://github.com/spinnaker/governance/issues/321
> feat(approver): Add ovidiupopa07 as oss-approver

- membership.yml
https://github.com/spinnaker/governance/issues/326 is approved
> feat(reviewer): Add danielas12 as reviewer.

- membership.yml
https://github.com/spinnaker/governance/issues/323 is approved
> feat(reviewer): Add edgarulg as reviewer

- membership.yml
https://github.com/spinnaker/governance/issues/338
> feat(approver): Add edgarulg as approver.

- membership.yml
https://github.com/spinnaker/governance/issues/327 request approved
> feat(reviewer): Add oscarmichelh as reviewer

- membership.yml
To move kirangodishala from reviewer to approver group.
Closes https://github.com/spinnaker/governance/issues/342
> To move kirangodishala from reviewer to approver group

- membership.yml
This commit adds myself, xibz, to the reviewer list based on issue #347
> update(membership): add xibz to reviewer list

- membership.yml
https://github.com/spinnaker/governance/issues/328
> feat(reviewer): Add sergio-quintero to reviewers

- membership.yml
Resolves request https://github.com/spinnaker/governance/issues/353
> chore(reviewer): Add christosarvanitis to reviewers

- membership.yml
To move siddhu-opsmx from reviewer to approver group.
[344](https://github.com/spinnaker/governance/issues/344)
> To move siddhu-opsmx from reviewer to approver group

- CODEOWNERS
- committee-technical-oversight/README.md
Closes https://github.com/spinnaker/governance/issues/356
> governance(toc): update TOC membership
