sig-summit/README.md
Trying out the new SIG lifecycle process.  
This is a request for a new SIG to bring the community into the planning and discussions for the Spinnaker Summit.
=> Adding Spinnaker Summit SIG Proposal

roadmap.md
I'd like the roadmap in the community repo to be theme-oriented. For tracking actual deliverables, we should adopt using Projects in `spinnaker/spinnaker`, with a project for each minor OSS release.
This will become a living document. SIGs and other organizations that are invested in contributing to major roadmap themes should open PRs to update this as necessary.
Currently some of these high-level themes are "led" by companies; which I don't particularly like. I'd like to replace these with working groups so that it's more inviting for community members to get involved in various efforts.
fyi @spinnaker/sc
=> docs(roadmap): Initial high-level roadmap

committee-steering/README.md
Propagating change from https://github.com/spinnaker/community/pull/21.
=> Replace Steven Kim with Andrew Phillips on SC.

sig-documentation/README.md
The documentation for Spinnaker can benefit from a group that looks at the documentation set holistically.
=> feat(sigs): Submit proposal for a documentation SIG

membership.yml
Current tracking of reviewers & approvers is spread in a bunch of places.
The desire is to move this into automation sourced from a file in the community repo.
This change does not include any automation, just provides an initial step.
The format on this file may change in the future, it's not prescribing anything.
Upon merging, the `reviewers.md` and `approvers.md` files in `spinnaker/spinnaker` will be deleted.
This also is another step towards cleanup of GitHub groups after splitting from Netflix ownership.
=> feat(github): Adding membership.yml manifest

governance.md
There was no explicit language that someone needs to be a Reviewer first. Also, there was no language around the process of moving from Reviewer to Approver, so I added some mentioning that there is no arbitrary timeline for moving between roles.
=> docs(governance): Update Approvers qualifications

README.md
We had a discussion in the Docs SIG about making the Community pages and repo more useful. This is the PR for the repo. Here's the PR for the pages: https://github.com/spinnaker/spinnaker.github.io/pull/1625
This PR does the following: 
- removes the forum and stack overflow links since they were not being actively monitored
- points people to Slack before filing an issue
- makes the repo a little more user friendly by adding `In this Repo`
=> chore(update): update the repo readme per Docs SIG meeting

sig-index.md
I'm adding the calendar info to the sig-index page since we're using that as the source of truth.
When the governance info was removed from spinnaker.io, the calendar info for SIGs disappeared with it (https://github.com/spinnaker/spinnaker.github.io/pull/1598).
=> chore(sigs): add sig calendar

README.md, governance.md, rfc/java11.md, rfc/plugins.md
I suppose the info from the README should move back to the website now?
=> docs(governance): the community repo was renamed to governance

rfc/eol_kubernetes_v1.md
Spinnaker currently supports both a V1 ("Legacy") and V2 ("Manifest-based") Kubernetes provider.
We should remove Spinnaker's V1 Kubernetes provider in Spinnaker version 1.21.
Supporting only one provider will improve the user experience for Spinnaker evaluators
and focus the Spinnaker/Kubernetes community on improving the V2 provider.
=> chore(rfc): Kubernetes V1 Provider EOL

rfc/halyard-lite.md
The current recommended way to deploy Spinnaker is by using Halyard. While Halyard has greatly simplified some aspects of installing and configuring Spinnaker, it has a number of shortcomings that are particularly apparent when deploying to Kubernetes. This document proposes replacing Halyard with a smaller tool that integrates better into the Kubernetes ecosystem.
=> feat(rfc): RFC to replace Halyard

sig-aws/README.md, sig-ci/README.md, sig-documentation/README.md, sig-kubernetes/README.md, sig-platform/README.md, sig-security/README.md, sig-spinnaker-as-code/README.md, sig-summit/README.md, sig-ui-ux/README.md
Someone in New Zealand was confused about what "Pacific" and "Eastern"
meant. I can't put a UTC time because the UTC time changes whenever we
shift to/from DST.
So I settled on US/Pacific, which should be unambiguous (as opposed to
"PST", which is both confusing and also technically only refers to the
winter time zone) and added a link to a time zone converter.
=> Add links to a time zone converter.

rfc/plugins-ui.md
Migrating this RFC from https://docs.google.com/document/d/16WmRSziTJsSBZ1kuKUfVleLAYMIxmfvz/edit
=> feat(rfc): plugins ui rfc

rfc/halyard-lite.md
* feat(rfc): Change status to approved 
I guess this became approved at the moment it had TOC signoff and was merged; let's officially update it.
* feat(rfc): Update Halyard Lite rfc to refer to kleat by name 
Since the RFC has publish, the new tool to replace Halyard has been named 'kleat'. Refer to it by this name in the RFC instead of by 'Halyard Lite'.
=> feat(rfc): Change halyard rfc to approved and add name

rfc/eol_kubernetes_v1.md
Also marks several of the documentation tasks complete. I'll wait until I've completed another medium batch of tasks before making another update PR against this RFC.
=> chore(rfc): mark Kubernetes V1 EOL RFC as accepted

governance.md
Remove reference to the Spinnaker community forum, as it has been deprecated.
=> docs(governance): Remove forum reference

sig-spinnaker-as-code/README.md
Stepping down as SIG lead, and nominating @luispollo to replace me.
@spinnaker/sc PTAL
=> feat(sig-as-code): add luispollo as lead, remove emjburns

rfc/account-management.md
Consistent account management across services and providers in Spinnaker.
=> feat(rfc): externalized account management

sig-spinnaker-as-code/README.md
Update description in subprojects for Spinnaker-as-Code SIG.
=> fix(doc): Update SIG Spinnaker-as-Code description and projects

membership.yml
Updating to reflect `approver` status as it appears I was not [added in April](https://github.com/spinnaker/governance/issues/120).  
T.T
=> Add allisaurus to membership.yml

sig-azure/README.md
This commit proposes the creation of the Azure SIG. Salesforce is interested in leading this effort,
we are hoping that other developers and operators from the community join this group.
=> Proposal for Azure SIG

sig-kubernetes/README.md
I'd like to propose @german-muzquiz take over my role as Kubernetes SIG lead. German has been critical in Armory's contribution to the Kubernetes provider and has worked with countless users to help make them successful. I have no doubt that he'll do a fantastic job leading in my place
=> chore(k8s-sig): SIG lead change for Kubernetes SIG

.github/ISSUE_TEMPLATE/plugin-ownership-transfer.md, sig-platform/community-donated-plugins.md
AWS & Autodesk have a number of plugins that they've been collaboratively developing and want to see community involvement with, however, they feel their company CLAs will be a hinderance to contributorship. The idea here is that the [`spinnaker-plugins`](https://github.com/spinnaker-plugins) organization can be used as a home for these plugins. Plugin authors will continue to own the maintenance and day-to-day operations of the repository via `write` access, however the TOC will have access to the org to help with membership as needed.
Question: Should plugin authors be given `write` or `admin` access for their plugin repository?
=> feat(docs): Process for donating community plugins

sig-azure/README.md
Add myself as SIG co-lead after successful nomination in 11/10/2020 Azure SIG meeting.
=> Additional Azure SIG lead

cx-sig-charter-draft.md, cx-sig-proposed-README.md
@ExitoLab and I are requesting approval to co-found a Contributor Experience SIG for the Spinnaker project. 
The Contributor Experience Special Interest Group (SIG) would be responsible for improving the experience of those who contribute upstream to the Spinnaker project. We do this by creating, and maintaining programs and processes that promote community health and reduce project friction while retiring those programs and processes that don’t. Being conscientious of our contributor base is critical to scaling the project, growing the ecosystem, and helping the project succeed.
Note to reviewers: It might make sense to squash the commits. There are lots of small updates as it was a collaborative effort.
=> Proposal for Contributor Experience SIG

.github/ISSUE_TEMPLATE/approver-application.md, .github/ISSUE_TEMPLATE/new-cloud-provider.md, .github/ISSUE_TEMPLATE/reviewer-application.md, CODEOWNERS, committee-technical-oversight/README.md
As previously announced, I'll be stepping away from the Spinnaker project and thus stepping down from the TOC effective today. This commit removes me from the various places where I am referenced as a member of the TOC.
=> chore(core): Remove ezimanyi as TOC member

rfc/manual.md
https://user-images.githubusercontent.com/72563935/106610189-76ecf680-658c-11eb-84d7-5f086947b891.mp4
| **Status**        | **Proposed**, Accepted, Implemented, Obsolete           |
| ------------- |-------------|
|  **RFC #**      | [spinnaker/deck#8818](https://github.com/spinnaker/deck/pull/8818) | 
| **Author(s)**      | 	[Rumit Rout (@rumit-opsmx)](https://github.com/rumit-opsmx), [Rajinder Siddhu (@siddhu-opsmx)](https://github.com/siddhu-opsmx)      | 
| **SIG / WG** | sig-ui     | 
If there are many pipelines it may be difficult for the user to serially check all the pipelines that are waiting for manual judgement. So we need a functionality which will filter out all the pipelines that require manual intervention.
To implement such a feature we added a stage filter ( Manual …
=> Design doc for Awaiting judgment filter and one click navigation to leaf node

membership.yml
Adding @nimakaviani to `oss-reviewers` per approvals in #223, and taking this opportunity to cleanup old entries in `netflix-new-hires`.
=> Add nimakaviani to oss-reviewers, cleanup netflix-new-hires

rfc/configurable-filters.md
| **Status**        | **Proposed**, Accepted, Implemented, Obsolete           |
| ------------- |-------------|
|  **RFC #**      | [spinnaker/deck#8819](https://github.com/spinnaker/deck/pull/8819)  | 
| **Author(s)**      | 	[Rumit Rout (@rumit-opsmx)](https://github.com/rumit-opsmx), [Rajinder Siddhu (@siddhu-opsmx)](https://github.com/siddhu-opsmx)      | 
| **SIG / WG** | sig-ui     | 
Spinnaker allows us to apply filters on pipelines execution page to help users view all the pipelines already executed or which are in execution. We have multiple parameters available by default to perform filter operation on pipeline executions i.e, Filter by status, Filter by pipeline Name etc.
In case of multiple pipelines, users may need other filters, aka custom filters to populate pipelines …
=> Design doc for configurable filter view

sig-platform/README.md
I've been active in the platform sig for the past few months, and am happy to co-lead with @link108 .
=> add David Byron as platform sig lead

CODEOWNERS, committee-steering/README.md, committee-technical-oversight/README.md, governance.md
One of them was out of date. Also fixed the outdated list in CODEOWNERS.
Also: updated the employers of Edgar and Matt, added some links, etc.
=> Remove duplicate Steering Committee membership.

committee-technical-oversight/README.md
My involvement with the Spinnaker community as a member of the Technical Oversight Committee 
has come to an end. 
Although I will remain a Spinnaker operator and fan, I have greatly exceeded the term limits.
👋  🍪
=> chore(*): Stepping down from TOC

rfc/feature-flag-backports.md
Amend the existing [backport policy][policy] to allow for new features or
backwards incompatible changes in behavior provided they are introduced with
opt-in feature flags. Details in the RFC.
[policy]: https://spinnaker.io/docs/community/contributing/code/releasing/#release-branch-patch-criteria
=> feat(process): add rfc for backport policy change

rfc/monorepo.md
This RFC proposes to consolidate all Spinnaker code into a single Git repository.
It also contains samples and instructions on how to preserve third-party forks, and maintain those forks moving forward.
=> RFC: Monorepo

rfc/java17.md
Time to move to Java 17, since Java 21 is out this year (!!!).
=> RFC: Java 17

sig-security/README.md
Old agenda notes appear to have been deleted.  It's unknown who the original owner was.  Also removing non-existing user.  AT THIS TIME an additional member for the security sig WOULD be ideal.
=> fix(sig): Removed bouncing email user & Fix notes links

rfc/pipeline-builder.md
This RFC proposes to add the `pipeline-builder` Java library to the set of Spinnaker repositories. `pipeline-builder` helps developers write and maintain pipelines by writing fluent, readable, and testable code as an alternative to the internal JSON format used by Spinnaker.
---
- Repository: https://github.com/nicolasff/pipeline-builder
- Tutorial: [examples/README.md](https://github.com/nicolasff/pipeline-builder/blob/main/examples/README.md)
- Examples: [7 classes, each building a pipeline](https://github.com/nicolasff/pipeline-builder/tree/main/examples/src/main/java/com/apple/spinnaker/examples)
=> RFC: pipeline-builder library
